FROM python:3.9

# Update the package list and install build-essential
RUN apt-get update && apt-get install -y build-essential

# Set the working directory
WORKDIR /code

# Copy the requirements file and install dependencies
COPY ./requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r requirements.txt

# Copy your application code
COPY ./ /code

# Start your application
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]

